galaxy_info:
  role_name: audit
  description: Audit system security state and detect configuration drift
  author: Anish Mondal
  company: self
  license: MIT
  min_ansible_version: "2.14"

dependencies: []

