galaxy_info:
  role_name: common
  description: Base system configuration and essential packages
  author: Anish Mondal
  company: self
  license: MIT
  min_ansible_version: "2.14"

dependencies: []

