galaxy_info:
  role_name: ssh_hardening
  description: Harden SSH configuration following security best practices
  author: Anish Mondal
  company: self
  license: MIT
  min_ansible_version: "2.14"

dependencies: []

