#SPDX-License-Identifier: MIT-0
# defaults file for roles/audit

---
audit_expected:
  ssh:
    PermitRootLogin: "no"
    PasswordAuthentication: "no"

  firewall:
    enabled: true

  users:
    - devops

