#SPDX-License-Identifier: MIT-0
# tasks file for roles/users

---
- name: Create devops user
  user:
    name: "{{ users_devops_user }}"
    shell: "{{ users_devops_shell }}"
    groups: sudo
    append: yes
    create_home: yes

- name: Create .ssh directory
  file:
    path: "/home/{{ users_devops_user }}/.ssh"
    state: directory
    owner: "{{ users_devops_user }}"
    group: "{{ users_devops_user }}"
    mode: "0700"

- name: Add SSH public key for devops user
  ansible.posix.authorized_key:
    user: "{{ users_devops_user }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

- name: Allow devops user passwordless sudo
  copy:
    dest: "/etc/sudoers.d/{{ users_devops_user }}"
    content: "{{ users_devops_user }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: "0440"

