---
- name: Check SSH root login setting
  shell: |
    set -o pipefail
    sshd -T | grep permitrootlogin

  register: audit_ssh_root_login
  changed_when: false

- name: Fail if root login is enabled
  fail:
    msg: "SECURITY DRIFT: Root login is enabled!"
  when: "'no' not in ssh_root_login.stdout"

